const {
  POA,
  DAI,
  POA_SOKOL,
  MAINNET,
  ROPSTEN,
  RINKEBY,
  KOVAN,
  TOMO_TESTNET,
  TOMO,
  POA_CODE,
  DAI_CODE,
  POA_SOKOL_CODE,
  MAINNET_CODE,
  ROPSTEN_CODE,
  RINKEBY_CODE,
  KOVAN_CODE,
  TOMO_TESTNET_CODE,
  TOMO_CODE,
  POA_DISPLAY_NAME,
  DAI_DISPLAY_NAME,
  POA_SOKOL_DISPLAY_NAME,
  MAINNET_DISPLAY_NAME,
  ROPSTEN_DISPLAY_NAME,
  RINKEBY_DISPLAY_NAME,
  KOVAN_DISPLAY_NAME,
  TOMO_TESTNET_DISPLAY_NAME,
  TOMO_DISPLAY_NAME,
  DROPDOWN_POA_DISPLAY_NAME,
  DROPDOWN_DAI_DISPLAY_NAME,
  DROPDOWN_POA_SOKOL_DISPLAY_NAME,
  DROPDOWN_MAINNET_DISPLAY_NAME,
  DROPDOWN_ROPSTEN_DISPLAY_NAME,
  DROPDOWN_RINKEBY_DISPLAY_NAME,
  DROPDOWN_KOVAN_DISPLAY_NAME,
  DROPDOWN_TOMO_TESTNET_DISPLAY_NAME,
  DROPDOWN_TOMO_DISPLAY_NAME,
  chainTypes,
} = require('./enums')

const { TEST, PROD } = chainTypes
const networks = {}

const TOMO_OBJ = {
  order: 1,
  chainType: PROD,
  providerName: TOMO,
  networkID: TOMO_CODE,
  displayName: TOMO_DISPLAY_NAME,
  displayNameDropdown: DROPDOWN_TOMO_DISPLAY_NAME
};
networks[TOMO_CODE] = TOMO_OBJ;
networks[TOMO] = TOMO_OBJ;


const TOMO_TESTNET_OBJ = {
  order:2,
  providerName: TOMO_TESTNET,
  networkID: TOMO_TESTNET_CODE,
  displayName: TOMO_TESTNET_DISPLAY_NAME,
  displayNameDropdown: DROPDOWN_TOMO_TESTNET_DISPLAY_NAME
};
networks[TOMO_TESTNET_CODE] = TOMO_TESTNET_OBJ;
networks[TOMO_TESTNET] = TOMO_TESTNET_OBJ;


const getNetworkDisplayName = key => networks[key].displayName

module.exports = {
  networks,
  getNetworkDisplayName,
}
